// Command OpenGovernmentPortal-mcp is an MCP server exposing the OpenGovernmentPortal
// SDK as MCP tools.
//
// Two tools are registered:
//
//	OpenGovernmentPortal_list  — list records of an entity
//	OpenGovernmentPortal_load  — load a single record of an entity
//
// Each accepts an `entity` argument and an optional `query` object
// (mapped 1:1 onto the SDK's reqmatch parameter).
//
// Transports:
//
//	-transport stdio   (default) — JSON-RPC over stdin/stdout, the
//	                   standard for spawnable agent-installed servers.
//	-transport http    — streamable HTTP on -addr (default :8080),
//	                   useful when sharing one running server between
//	                   multiple agents.
//
// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/open-government-portal-sdk/go"
)

func main() {
	transport := flag.String("transport", "stdio", "transport: stdio | http")
	addr := flag.String("addr", ":8080", "listen address for http transport")
	flag.Parse()

	// Configure from the environment: OPEN_GOVERNMENT_PORTAL_APIKEY carries the API key and
	// OPEN_GOVERNMENT_PORTAL_BASE optionally overrides the API base URL (e.g. production).
	// Both injectable by a secrets vault. Unset -> nil config defaults.
	var opts map[string]any
	if apikey := os.Getenv("OPEN_GOVERNMENT_PORTAL_APIKEY"); apikey != "" {
		opts = map[string]any{"apikey": apikey}
	}
	if base := os.Getenv("OPEN_GOVERNMENT_PORTAL_BASE"); base != "" {
		if opts == nil {
			opts = map[string]any{}
		}
		opts["base"] = base
	}
	client := sdk.NewOpenGovernmentPortalSDK(opts)
	server := mcp.NewServer(
		&mcp.Implementation{
			Name:    "open-government-portal",
			Version: "0.0.0",
		},
		nil,
	)
	registerTools(server, client)

	switch *transport {
	case "stdio":
		if err := server.Run(context.Background(), &mcp.StdioTransport{}); err != nil {
			log.Fatalf("stdio server: %v", err)
		}
	case "http":
		handler := mcp.NewStreamableHTTPHandler(
			func(r *http.Request) *mcp.Server { return server },
			nil,
		)
		log.Printf("MCP streamable HTTP server listening on %s", *addr)
		if err := http.ListenAndServe(*addr, handler); err != nil {
			log.Fatalf("http server: %v", err)
		}
	default:
		fmt.Fprintf(os.Stderr, "unknown transport %q (want stdio | http)\n", *transport)
		os.Exit(2)
	}
}
